import Head from 'next/head';
import { useRouter } from 'next/router'
import React from 'react'

const TVDetailsPage = () => {
    const router = useRouter();
    const { tvId } =router.query
  return (
      <main>
        <Head>
            <title>TV Details</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <div className='flex justify-center'>dfdfd {tvId}</div>
      </main>
    
  )
}

export default TVDetailsPage