import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Dashboard from '../components/Dashboard'
import Navbar from '../components/Navbar'
import Sidebar from '../components/Sidebar'
import { Movie } from '../interface'
import { getNowPlaying, getPopular, getTopRated, getTrendingMovies } from './api/movie'

interface IMovie {
  trendingMovies:Movie[];
  nowPlayingMovies:Movie[];
  topRatedMovies:Movie[];
  popularMovies:Movie[];
}

const Home = ({ trendingMovies,nowPlayingMovies,topRatedMovies,popularMovies }:IMovie) => {

  return (
    <div className='overflow-hidden'>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        {/* <Sidebar /> */}
        <Navbar />
        <Dashboard topRatedMovies={topRatedMovies} trendingMovies={trendingMovies} nowPlayingMovies={nowPlayingMovies} popularMovies={popularMovies} />

          
          

     
    
    </div>
  )
}

export const getStaticProps = async() => {
  const [trendingMovies,nowPlayingMovies,topRatedMovies,popularMovies] = ([await getTrendingMovies(),await getNowPlaying(),await getTopRated(),await getPopular()]);


  
  return {
    props:{
      trendingMovies,
      nowPlayingMovies,
      topRatedMovies,
      popularMovies
    }
  }
}

export default Home
